process-engine/ci_tools

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, .npmignore, README.md, gulpfile.js, package.json, tsconfig.json, tslint.json
**Changes:**
1. Add basic project structur
2. Add templates
**Issues:**
PR: #1
---
See the [examples](#example) for inspiration.
<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>
To get your commit message, just copy the first part of this pull request.
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...
**Issues:**
Closes …
=> :tada: Add Basic Project Layout

README.md, package.json, src/is-nuget-package-published.ts
**Changes:**
1. Implement nuget check script
2. Update README
**Issues:**
PR: #4
---
See the [examples](#example) for inspiration.
<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>
To get your commit message, just copy the first part of this pull request.
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...
**Issues:**
Closes …
=> :sparkles: Implement Script To Check For Published NuGet Packages

.eslintrc.json, azure-pipelines.yml, package-lock.json, package.json, src/ci_tools.ts, src/create-changelog/index.ts, src/create-changelog/pull_requests.ts, src/create-changelog/releases.ts, src/increment-version/git.ts, src/increment-version/index.ts, src/increment-version/previous_stable_version.test.ts, src/increment-version/previous_stable_version.ts
Dieser PR bildet die Grundlage zur Automatisierung der Erstellung der Alpha- und Beta-Changelogs (diese muss perspektivisch vollständig automatisch ablaufen).
=> Add create-changelog command

package-lock.json, package.json, src/commands/create-changelog.ts, src/github/pull_requests.ts
:tada: **Thanks for submitting this Pull Request**
Please provide a list including your changes.
To help us to create a meaningful Changelog, we agreed
to use an emoji-based commit-style. Use the [Emojis](#emojis)
we provided below.
Fill out the following, provide reference to issues
and this PR- we will use this as merge commit message-body
and the title of this PR as commit-headline:
---
**Changes:**
1. Change 1
2. Change 2
3. (...)
**Issues:**
Closes #Issue
Closes #Issue
Closes (...)
PR: #PullRequest
---
See the [examples](#example) for inspiration.
<details>
<summary>
:warning: Before merging please click here to expand and follow …
=> Release new beta-version

azure-pipelines.yml, package-lock.json, package.json
:tada: **Thanks for submitting this Pull Request**
Please provide a list including your changes.
To help us to create a meaningful Changelog, we agreed
to use an emoji-based commit-style. Use the [Emojis](#emojis)
we provided below.
Fill out the following, provide reference to issues
and this PR- we will use this as merge commit message-body
and the title of this PR as commit-headline:
---
**Changes:**
1. Change 1
2. Change 2
3. (...)
**Issues:**
Closes #Issue
Closes #Issue
Closes (...)
PR: #PullRequest
---
See the [examples](#example) for inspiration.
<details>
<summary>
:warning: Before merging please click here to expand and follow …
=> Release new Beta version

README.md, src/commands/create-changelog.ts, src/commands/increment-version.ts, src/commands/npm-ci-except.ts
=> Improve docs

Jenkinsfile, azure-pipelines.yml, package-lock.json, package.json, src/commands/commit-and-tag-version.ts, src/commands/internal/setup-git-and-npm-connections.ts, src/commands/npm-install-only.ts, src/commands/prepare-version.ts, src/commands/publish-npm-package.ts, src/commands/update-github-release.ts
Dieser PR enthält finale Änderungen, um `ci_tools` auf verschiedenen CI-Systemen lauffähig zu machen.
=> Adapt tools to ci

package.json, src/versions/previous_stable_version.ts
Fixes a regression when a tag name does not match semver schema.
=> Fix semver comparison

src/commands/internal/create-changelog.ts, src/github/pull_requests.ts
Filters the found issues to only include issues referenced in the merged PRs body texts.
=> Filter issues by merged pull requests

src/commands/upgrade-dependencies-with-pre-versions.ts
**Changes:**
1. Log the npm command only if the versionsToInstall array has entries.
2. Add newline to console.logs to improve readability
PR: #32 
---
=> ✨ Log the npm command if versions are found

src/commands/internal/create-changelog.ts
1. Add Error Message When Changelog Creation Fails
PR: #39
=> ✨ Add Error Message When Changelog Creation Fails

src/commands/internal/create-release-announcement.ts
1. Use Correct Release Version
2. Add Error Message When Release Note Creation fails
PR: #40
=> 🐛 Fix Creating Release Notes

.github/workflows/publish.yml
1. Publish feature branch version
PR: #43 
=> ✨Publish feature branch versions on npm

src/ci_tools.ts, src/commands/get-version.ts, src/versions/package_version.test.ts, src/versions/package_version.ts
1. Add getMajorPackageVersion function
2. Add get-version command
PR: #42 
`ci_tools get-version`
`ci_tools get-version --major`
=> ✨Add get version command

src/commands/internal/create-changelog.ts, src/versions/git_helpers.ts
1. Cancel Changelog Creation When StartRef Not Set
PR: #44
=> 🐛 Cancel Changelog Creation When StartRef Not Set

src/ci_tools.ts, src/commands/copy-and-commit-version-for-subpackage.ts
1. Add Command to Copy Package Version to Subpackage
PR: #45
=> ✨ Add Command to Copy Package Version to Subpackage

src/versions/package_version.ts
1. Fix find csproj on macos
2. Fix find csproj on Windows
PR: #48 
=> 🐛Fix getting csproj path

src/ci_tools.ts, src/commands/commit-and-tag-version.ts, src/commands/copy-and-commit-version-for-subpackage.ts, src/commands/get-version.ts, src/commands/internal/create-changelog.ts, src/commands/internal/create-release-announcement.ts, src/commands/prepare-version.ts, src/commands/publish-npm-package.ts, src/commands/publish-releasenotes-on-slack.ts, src/commands/set-version.ts, src/commands/update-github-release.ts, src/versions/git_helpers.ts, src/versions/package_version.test.ts, src/versions/package_version.ts, src/versions/retry_run.ts
1. Use mode argument instead of environment variable
PR: #47 
=> ✨Use mode argument instead of environment variable

src/versions/package_version.test.ts, src/versions/package_version.ts, test/fixtures/dotnet-simple/ProcessEngine.Client.csproj, test/fixtures/node-simple/package.json, test/test_functions.ts
Adds basic tests for the new `dotnet` mode.
=> Add basic tests for dotnet mode

package.json, src/commands/commit-and-tag-version.ts, src/commands/copy-and-commit-version-for-subpackage.ts, src/commands/get-version.ts, src/commands/prepare-version.ts, src/commands/publish-releasenotes-on-slack.ts, src/commands/update-github-release.ts, src/versions/package_version/dotnet.ts, src/versions/retry_run.ts
Sollte #59 fixen.
Muss wahrscheinlich "manuell" mit der Feature-Version getestet werden.
=> Fix error handling for Octokit

src/commands/commit-and-tag-version.ts, src/commands/prepare-version.ts, test/integration/smoke.dotnet.test.ts, test/integration/smoke.node.test.ts
Behebt #55
Ich würde mit Merge dieses PRs dann auch mal Version `3.0.0-beta.1` releasen.
=> Fix dry run for commit and tag version

src/commands/publish-npm-package.ts
1. Increase total amount of retries with npm view before failing ensureVersionIsAvailable
=> Increase total amount of retries with npm view before failing ensureVersionIsAvailable

package-lock.json, package.json, src/commands/internal/create-release-announcement.ts, src/commands/publish-npm-package.ts, src/product_name/package_product_name/dotnet.ts, src/product_name/package_product_name/node.ts, src/product_name/package_product_name/python.ts, src/product_name/product_name.test.ts, src/product_name/product_name.ts, test/fixtures/dotnet-simple/ProcessEngine.Client.csproj, test/fixtures/python-simple/setup.py
=> Betarelease v3.1.0 beta.2

src/commands/internal/create-release-announcement.ts
Add changelog link to release notification when no start ref is given
=> Add changelog link to release notification when no start ref is given
