.eslintrc.json, azure-pipelines.yml, package-lock.json, package.json, src/ci_tools.ts, src/increment-version/git.ts, src/increment-version/increment_version.test.ts, src/increment-version/increment_version.ts, src/increment-version/index.ts, src/increment-version/package_version.ts, src/increment-version/shell.ts, src/legacy/create-github-release.ts, src/legacy/is-nuget-package-published.ts, tsconfig.json
Fügt eine `bin` namens `ci_tools` hinzu, welche als erstes Subcommand `increment-version` kennt.
Die Binaries `create-github-release` und `is-nuget-package-published` werden natürlich weiterhin geführt.
=> Add increment-version command to ci_tools CLI

package-lock.json, package.json, src/ci_tools.ts, src/commands/npm-ci-except.ts
Fügt ein Kommando hinzu, dass alle Deps per `npm ci`, aber zusätzlich die Deps, die mit den angegebenen Namen anfangen, per `npm install` aktualisiert (das ist wünschenswert, wenn wir bspw. Pakete per Tag referenziert haben).
Dieser Schritt soll perspektivisch den `npm ci`-Step in unserer CI ersetzen.
```
ci_tools npm-ci-except @process-engine/ @essential-projects/
```
würde bspw. alle Pakete per `npm ci` installieren und anschließend einzeln alle Pakete, die entweder mit `@process-engine/` oder `@essential-projects/` anfangen, per `npm install` hochziehen.
=> Add command npm-ci-except

.eslintrc.json, src/ci_tools.ts, src/commands/increment-version.ts, src/commands/update-github-release.ts, src/versions/increment_version.ts
Fügt ein Kommando `update-github-release` hinzu, dass Titel und Text eines GitHub-Releases setzt.
```
ci_tools update-github-release --version-tag "v1.2.0" --title "RELEASE! v1.2.0 😎" --text "Dies ist ein Test!!!"
```
Das Kommando funktioniert deklarativ, soll heißen, es ist unerheblich, ob zu dem gegebenen Tag schon ein Release auf GitHub existiert (in diesem Fall wird das bestehende so geupdatet, dass der angegebene Zustand nach Ausführung des Kommandos erreicht ist).
=> Add "update-github-release" command

src/ci_tools.ts, src/commands/npm-install-only.ts
Renames the `npm-ci-except` command to `npm-install-only`. Does no longer run `npm ci` before
installing the pattern matches packages via `npm install` to provide more flexibility to the CI.
```
$ ci_tools npm-install-only @process-engine/
```
is also probably more "self explanatory".
=> Rename npm-ci-except -> npm-install-only

package-lock.json, package.json, src/commands/update-github-release.ts
Fügt einen Switch `--assets` hinzu, um Assets an ein GitHub-Release anzufügen.
Das Kommando ist deklarativ, idempotent und unterstützt "glob pattern". Der Nutzer gibt an, welche Dateien Teil des GitHub-Releases sein sollen und das Kommando sorgt dafür, dass sie es sind. 
```
ci_tools update-github-release  --version-tag v2.0.0 \
--assets dist/bpmn-studio-setup-*.exe \
--assets dist/bpmn-studio-setup-*.exe.blockmap \
--assets dist/bpmn-studio-*-mac.zip \
--assets dist/bpmn-studio-*-x86_64.AppImage \
--assets dist/bpmn-studio-*.dmg \
--assets dist/bpmn-studio-*.dmg.blockmap \
--assets dist/latest-mac.yml \
--assets dist/latest.yml
```
Wie das Beispiel zeigt, müssen die Switches `title` und `text` nicht angegeben werden, so dass ein Release unter Angabe seines Versionstags leicht um Assets …
=> Add assets option update GitHub release command

package-lock.json, package.json, src/ci_tools.ts
Führt das gegebene Kommando nur aus, wenn der User sich NICHT auf einem "primary branch"  (`develop`, `beta`, `master`) befindet.
```bash
$ ci_tools npm-install-only --except-on-primary-branches @process-engine/
```
Diese Option soll helfen auf Feature-Branches npm-Tags nutzen zu können, aber auf `develop`, `beta` und `master` ausschließlich `npm ci` laufen zu lassen.
=> Add --except-on-primary-branches switch

src/cli/shell.ts, src/commands/npm-install-only.ts
**Changes:**
1. Use 'save-exact' for 'npm-install-only'
PR: #22
- **Have a look at [this pr](https://github.com/process-engine/process_engine_runtime/pull/392)**
=> 🐛 Use 'save-exact' for 'npm-install-only'

src/commands/internal/create-changelog.ts, src/git/git.ts, src/github/pull_requests.ts, src/versions/previous_stable_version.test.ts
Uses the commit history to determine which PRs were merged (rather than a timestamp,
which breaks during feature-freeze).
Caveats: Does not pick up commits that were applied using `git cherry-pick`.
=> Fix identifying PRs for create-changelog

src/commands/prepare-version.ts
Wenn man aktuell von bspw. `beta` nach `master` mergt, um aus Version `2.0.0-beta.1` die Version `2.0.0` zu machen, dann brechen die CI Tools ab, weil sie denken "Da sind keine Änderungen im Vergleich zu `2.0.0-beta.1`, also brechen wir hier mal ab.".
Die Änderungen dieses PRs bedingen einen Vergleich des Release-Kanals, um festzustellen, ob trotz gleicher Inhalte eine neue Version gebaut werden muss.
=> Add release channel comparison to prepare-version

package.json, src/cli/shell.ts, src/commands/commit-and-tag-version.ts, src/commands/prepare-version.ts, src/commands/publish-npm-package.ts, src/versions/retry_run.ts
Soll dafür sorgen, dass ein wiederholter CI Build Job bzgl. der nicht erfolgreich ausgeführten Steps wiederholt wird und an allen anderen Steps *nicht* scheitert.
=> ✨ Make ci_tools work for retried builds

src/ci_tools.ts, src/commands/upgrade-dependencies-with-pre-versions.test.ts, src/commands/upgrade-dependencies-with-pre-versions.ts, src/versions/parse_version.test.ts, src/versions/parse_version.ts
Aus der Doku:
> Upgrades alpha- and beta-pre-versions for the packages with a name starting with one of the given args.
>
> Example:
>
>      ci_tools upgrade-dependencies-with-pre-versions @process-engine/
>
> Upgrades all deps starting with `@process-engine/` if there is a newer version available in their
> release channel or if a stable version of the same base version has been released.
>
> This command does not change base version!
Dieses Programm ist nur für das "Anheben der Nummer bei Pre-Releases" bzw. das Upgrade auf die entsprechende stabile Version zuständig.
Der automatische Wechsel der Dependency-Einträge von Alpha auf Beta ist nicht Gegenstand *dieses* PRs.
=> Add upgrade-dependencies-with-pre-versions command

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, src/commands/publish-npm-package.ts
Implement `retry` for `publish-npm-package` command version verification.
This retry will run the follow-up `npm view` command up to 20 times, with a timeout of 500ms between each try.
If the max number of retries is used up and the package is still not visible at npm, the publish is regarded as a failure.
PR: #33
Unfortunately, this can only be tested when npm is hanging again. 
If that is the case, the published version would not be initially visible.
Normally, the command would immediately throw an error, but with the retry-loop in place, it will now retry a number of times, before giving up.
Each retry should be visible in the console.
=> ✨ Implement retry for publish-npm-package

src/cli/shell.ts, src/git/git.ts
Sorgt dafür, dass Commit Messages mit Backticks escaped werden (damit sie nicht von Bash, zsh, o.ä. interpretiert werden). Escaped aktuell drei Steuerzeichen:
```
` 
$
"
```
Beispiel für Commits mit Backticks: https://github.com/process-engine/process_engine_runtime/pull/467
=> Fix injection possibility through commit messages

src/commands/npm-install-only.ts
1. Fix bug where `Object.keys` does not work on null or undefined
PR: #37 
use `./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/` on a package which does not have any dependencies or devDependencies e.g. solutionexplorer.contracts
=> 🐛 Fix bug where npm-install-only does not work correctly

src/ci_tools.ts, src/commands/internal/create-changelog-announcement.ts, src/commands/internal/create-release-announcement.ts, src/commands/publish-releasenotes-on-slack.ts, src/slack/notifier.ts
1. Add Changelog Announcement Creation
2. Add Slack Support
3. Add 'publish-releasenotes-on-slack' Command
PR: #38
> Create an incoming webhook via https://slack.com/apps/A0F7XDUAZ-incoming-webhooks
- Link this PR into BPMN Studio
- Run `SLACK_WEBHOOK=<incoming webhook url> ci_tools publish-releasenotes-on-slack`
=> ✨ Add Release Announcement Support

package.json, src/git/git.ts
1. Add --allow-empty argument to the git commit command
PR: #41 
=> ✨Add --allow-empty argument to git commit command

package.json, src/commands/get-version.ts, src/commands/prepare-version.ts, src/commands/set-version.ts, src/commands/upgrade-dependencies-with-pre-versions.test.ts, src/npm/tag.test.ts, src/versions/increment_version.test.ts, src/versions/package_version.test.ts, src/versions/package_version.ts, src/versions/package_version/dotnet.ts, src/versions/package_version/node.ts, src/versions/parse_version.test.ts, src/versions/previous_stable_version.test.ts
Packt alle `dotnet`-spezifischen Funktionen in eine Datei und alle `node`-speifizischen in eine andere.
=> Separate dotnet and node functions into modules

.gitignore, src/commands/update-github-release.ts
I recently encountered the following error:
This happened because the "data" object from the parsed error message did not contain an "errors" property. Consequently, the error that actually occurred was swallowed up and replaced by this most unhelpful error shown above.
By use of null-coalescing, we are now able to handle such cases.
PR: #58
Kinda hard to test. Just "hope" that one of your GitHub releases fails, I guess...
=> 🐛 Fix error handling for "updateExistingRelease"

src/commands/commit-and-tag-version.ts, src/contracts/modes.ts, src/versions/package_version.ts, src/versions/package_version/dotnet.ts, test/assert_functions.ts, test/integration/smoke.dotnet.test.ts
Gleiches Spiel wie gestern, nur diesmal für .NET Projekte.
Fügt also Smoke-Tests für die `prepare-version`- und `commit-and-tag-version`-Kommandos im Modus `dotnet` (a.k.a. `package.json`) hinzu.
Zum Testen:
```shell
npm run test:integration
```
=> Add integration tests for dotnet mode

src/ci_tools.ts, src/commands/replace-dist-tags-with-real-versions.ts, src/git/git.ts, src/npm/dependency.test.ts, src/npm/dependency.ts
1. Add a new command "replace-dist-tags-with-real-versions"
2. Add npm-dependency-related functions and tests
3. Add an optional "pathspec" parameter to "isDirty" (git-related function)
PR: #66
1. `npm i -g @process-engine/ci_tools@feature~add-command-fail-on-pre-version-dependencies`
2. Navigate to a repository
3. Use dist tags (e.g. "alpha", "beta" or "feature~xyz") for packages
4. Run `ci_tools replace-dist-tags-with-real-versions --dist-tags-to-replace [<dist tag>...] [<package-pattern>...]`
5. Check if dist tags were replaced with real versions
<details>
<summary>First example</summary>
Command:
```
ci_tools replace-dist-tags-with-real-versions @atlas-engine/ -d feature
```
Dependencies in package.json before command execution:
```
@atlas-engine/iam: feature~new_awesome_feature …
```
=> ✨ Add new command to replace dist-tags with real versions

src/ci_tools.ts, src/commands/commit-and-tag-version.ts, src/commands/copy-and-commit-version-for-subpackage.ts, src/commands/get-version.ts, src/commands/prepare-version.ts, src/commands/publish-releasenotes-on-slack.ts, src/commands/set-version.ts, src/commands/update-github-release.ts, src/contracts/modes.ts, src/versions/package_version.ts, src/versions/package_version/python.ts
1. Add support for Python projects
2. Add missing documentation for "--mode" option. Some commands lack documentation for their other options which I won't fix in this PR, but I created an issue regarding that matter (#69).
PR: #68 
1. `npm i -g @process-engine/ci_tools@feature~python_versioning_support`
1. Navigate to a Python project (e.g. https://github.com/atlas-engine/process_engine-python)
1. `ci_tools prepare-version --mode python --allow-dirty-workdir`
1. A new version should have been written to setup.py
=> ✨ Add support for Python projects

src/commands/replace-dist-tags-with-real-versions.ts
1. Replace "fs-extra" with "fs" because "fs-extra" is a dev dependency
PR: #73
=> 🐛 Don't use dev dependencies in runtime code

package-lock.json, package.json, src/commands/get-version.ts
1. Es existieren nun zwei neue Optionen für den Befehl "get-version":
1. `--release-channel-name` Gibt den Release-Kanal-Namen zurück (z.B. "alpha" für "1.2.3-alpha.5")
2. `--release-channel-number` Gibt die Release-Kanal-Nummer zurück (z.B. "5" für "1.2.3-alpha.5")
2. Es wurden Sicherheitslücken durch das Aktualisieren von Abhängigkeiten behoben
PR: #76 
```
npm i -g @process-engine/ci_tools@feature~enhance_get_version
ci_tools get-version --release-channel-name
```
=> ✨ Add --release-channel-(name|number) option for get-version

package-lock.json, package.json
1. Fix security vulnerabilities by upgrading dependencies
```
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Remote Code Execution                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > serialize-javascript                                 │ …
```
=> 🔒 Fix security vulnerabilities

src/commands/internal/create-release-announcement.ts
Im techn. Meet besprochen - entfernt den `productName` aus den Release-Announcements, da dieser bereits als Produkt-Name in dem Announcer-Name wiedergespiegelt wird und teilweise zu technisch für ein derartiges Announcement ist. Wir wollen damit die Announcements übersichtlicher gestalten. Im Zuge dessen werden einige Announcer-Namen angepasst, damit diese den Produkt-Namen besser wiederspiegeln.
Vorher:
**@atlas-engine/fullstack_server v10.2.0 was released!**
The new version includes the following changes:
- :bug: Allow regular users to run processes with ExternalTasks
- :bug: Avoid database creation if database exists
- :bug: Fix null/undefined external task payload
For a more detailed changelog have a look at: http://github.com/atlas-engine/AtlasEngine/releases/tag/v10.2.0
Jetzt: …
=> Remove productName from releaseHeadline

src/commands/internal/create-changelog.ts, src/commands/internal/create-release-announcement.ts, src/github/pull_requests.ts
1. Fügt den Prefix `Breaking:` an Changelog Einträge für geschlossene PRs mit `Breaking Change`-Label hinzu.
1. Fügt den Prefix `Breaking:` an Release Announcement Einträge für geschlossene PRs mit `Breaking Change`-Label hinzu.
=> Add Breaking text to changelog and release announcement

README.md, src/ci_tools.ts, src/commands/internal/create-changelog.ts, src/commands/internal/create-release-announcement.ts
Ändert die Darstellung von Release-Announcements auf folgendes Format (das "es gibt breaking changes" am Anfang ist natürlich kontextabhängig):
Insbesondere die Verlinkung der PRs erscheint mir ein Gewinn.
Zusätzlich wird, wie bei anderen "internen" Kommandos, das Modul "create-release-announcement" als Kommando zur Verfügung gestellt, um ein manuelles Testen des resultierenden Textes zu vereinfachen.
=> Highlight breaking changes in release announcements

src/commands/internal/create-changelog.ts, src/git/git.ts
Fügt den Release Notes von Betas zusätzliche Zwischenüberschriften hinzu, um leichter zu erkennen, was in welcher Beta hinzugekommen ist:
Closes #74
=> Add previous pre version steps in beta releases

src/commands/internal/create-changelog.ts
Fixt einen Typo bei der Erstellung der Changelogs, wodurch
```
11.0.0-beta.7 (this release)
```
zu
```
v11.0.0-beta.7 (this release)
```
korrigiert wird (man beachte das vorangestellte `v`).
=> Fix release header for current release in create-changelog

src/commands/internal/create-release-announcement.ts
Korrigiert einen Fehler in der PR-URL, die für Release-Announcements generiert wird. Es muss `pull` und nicht `pulls` heißen um direkt auf einen PR zu verlinken.
Siehe bspw:
[vorher](https://github.com/atlas-engine/AtlasEngine/pulls/267) `https://github.com/atlas-engine/AtlasEngine/pulls/267`
[nachher](https://github.com/atlas-engine/AtlasEngine/pull/267) `https://github.com/atlas-engine/AtlasEngine/pull/267`
=> Fix release announcement pr url

package.json, src/commands/update-github-release.ts
1. Fix wrong status code
2. Return the correct `success`
3. Provide title and text 
PR: #94 
try to use 
`ci_tools update-github-release 
--assets <your-file>`
if the release does not exist yet.
Before this PR, the release would be created while executing this command, but no assets were uploaded.
=> Fix updating GitHub release if no release exist

src/commands/copy-and-commit-version-for-subpackage.ts, src/commands/publish-npm-package.ts, src/git/git.test.ts, src/git/git.ts, src/versions/package_version/dotnet.ts
Die CI Tools publishen alpha Versionen eines npm Pakets nicht unter dem Alpha-Tag, wenn der Build über ein Tag/Release Event getriggert wurde, sondern unter z.B. `refs~tags~v1.0.0-alpha.19` (Atlas Studio). 
Das liegt daran dass im GitHub Kontext des Runners `github.ref` in diesem Fall nicht `refs/heads/<branchname>` sondern `refs/tags/<tagname>` ist. 
1. Passt die getGitBranch Funktion an sodass im Falle von `refs/tags/<tagname>` der Branchname zurückgegeben wird, vorrausgesetzt der `<tagname>` ist Semver konform. 
2. Falls der Branchname trotzdem nicht ermittelt werden kann, wird die Package Version ausgelesen und der Release Kanal zum Branchnamen gemappt.
PR: #96 
=> Fix tagging npm package if workflow was started by tag event
